<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kwz</groupId>
        <artifactId>wz-spring-boot-starter</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>wz-spring-boot-starter-monitor</artifactId>
    <name>wz-spring-boot-starter-monitor</name>
    <description>监控 — Actuator、Prometheus、健康检查</description>
    <dependencies>
        <dependency>
            <groupId>com.kwz</groupId>
            <artifactId>wz-spring-boot-starter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
