<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.ttsukitt</groupId>
    <artifactId>wz-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>wz-dependencies</name>
    <description>BOM — 统一版本管理</description>
    <url>https://github.com/TTsukiTT/wz-spring-boot-starter/tree/main/wz-dependencies</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>weizan</id>
            <name>weizan</name>
            <url>https://github.com/TTsukiTT</url>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/TTsukiTT/wz-spring-boot-starter.git</connection>
        <developerConnection>scm:git:https://github.com/TTsukiTT/wz-spring-boot-starter.git</developerConnection>
        <url>https://github.com/TTsukiTT/wz-spring-boot-starter/tree/main/wz-dependencies</url>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <revision>1.0.2</revision>
        <spring-boot.version>3.4.5</spring-boot.version>
        <mybatis-plus.version>3.5.9</mybatis-plus.version>
        <redisson.version>3.41.0</redisson.version>
        <hutool.version>5.8.35</hutool.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.version>1.18.36</lombok.version>
        <tlog.version>1.5.2</tlog.version>
        <jjwt.version>0.12.6</jjwt.version>
        <flatten-maven-plugin.version>1.6.0</flatten-maven-plugin.version>
        <maven-gpg-plugin.version>3.2.7</maven-gpg-plugin.version>
        <central-publishing-maven-plugin.version>0.6.0</central-publishing-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 内部模块 -->
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-log</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-oss</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-mq</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-job</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-monitor</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ttsukitt</groupId>
                <artifactId>wz-spring-boot-starter-test</artifactId>
                <version>${revision}</version>
            </dependency>

            <!-- 第三方 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yomahub</groupId>
                <artifactId>tlog-core</artifactId>
                <version>${tlog.version}</version>
            </dependency>
            <dependency>
                <groupId>com.yomahub</groupId>
                <artifactId>tlog-common</artifactId>
                <version>${tlog.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>ossrh</flattenMode>
                    <pomElements>
                        <dependencyManagement>keep</dependencyManagement>
                        <properties>keep</properties>
                    </pomElements>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg-plugin.version}</version>
                        <configuration>
                            <passphraseServerId>gpg-passphrase</passphraseServerId>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central-publishing-maven-plugin.version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>central-publish</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>publish</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                            <autoPublish>true</autoPublish>
                            <waitUntil>published</waitUntil>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
