<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.kwz</groupId>
        <artifactId>wz-spring-boot-starter</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>wz-spring-boot-starter-web</artifactId>
    <name>wz-spring-boot-starter-web</name>
    <description>Web 层 — 全局异常、统一响应、CORS、参数校验</description>

    <dependencies>
        <dependency>
            <groupId>com.kwz</groupId>
            <artifactId>wz-spring-boot-starter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kwz</groupId>
            <artifactId>wz-spring-boot-starter-log</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
